[TOC]

# 1. 에러 (Error)



### 1-1. 문법 에러 (Syntax Error)

> 문법 에러가 발생하면 프로그램은 실행되지 않는다.
>
> `SyntaxError`  키워드와 함께 `파일이름` `줄번호`  `^`  로 문법 에러가 발생한 위치를 알려준다.
>
> 단, `^` 가 항상 정확한 오류 발생 지점을 알려 주지 않으므로, `^` 가 지정한 위치 전후를 살펴보아야 한다.

```python
if True:
    print('참')
else
    print('거짓')
```

```
  File "<ipython-input-1-e832de0e3f84>", line 4
    else
        ^
SyntaxError: invalid syntax
```



---



### 1-2. 예외 (Exception)

> 예상하지 못한 상황을 맞이하면, 프로그램은 실행을 멈춘다.

- `ZeroDivisionError` : '0'으로 숫자를 나눌 때 발생한다.

```python
print(5/0)
```

```
Traceback (most recent call last):
  File "homework4.py", line 1, in <module>
    print(5/0)
ZeroDivisionError: division by zero
```



- `NameError` : 변수가 정의되지 않았을 때 발생한다. 

```python
print(name)
```

```
Traceback (most recent call last):
  File "homework4.py", line 1, in <module>
    print(name)
NameError: name 'name' is not defined
```



- `TypeError` : 타입이 다른 변수끼리 연산하려 할 때 발생한다. (자동 형변환 제외)

```python
a = '123'
print(1+a)
```

```
Traceback (most recent call last):
  File "homework4.py", line 2, in <module>
    print(1+a)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```



- `IndexError` : 범위를 넘어가는 인덱스를 조회할 때 발생한다.

```python
a = [1,2,3,4,5]
print(a[5])
```

```
Traceback (most recent call last):
  File "homework4.py", line 2, in <module>
    print(a[5])
IndexError: list index out of range
```



- `KeyError` : 딕셔너리에 없는 key로 접근할 때 발생한다.

```python
a = {'1반':10, '2반':20}
print(a['3반'])
```

```
Traceback (most recent call last):
  File "homework4.py", line 2, in <module>
    print(a['3반'])
KeyError: '3반'
```



- `ModuleNotFoundError` : 모듈의 이름이 잘못되었을 때 발생한다.

```python
import randoms
a = random.choice([1,2,3,4,5])
print(a)
```

```
Traceback (most recent call last):
  File "homework4.py", line 1, in <module>
    import randoms
ModuleNotFoundError: No module named 'randoms'
```



- `ImportError` : 패키지는 찾았지만, 안에 import하려는 모듈이 없을 때 발생한다.

```python
# Animal.py
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

# example.py
from Animal import Bird
```

```
Traceback (most recent call last):
  File "homework4.py", line 1, in <module>
    from Animal import Bird
ImportError: cannot import name 'Bird' form 'Animal'
```



---



# 2. 예외 처리 (Exception Handling)

### 2-1. try & except

> `try`  아래의 code block이 실행되고, **예외가 발생하면 남은 부분을 수행하지 않고 `except`  를 실행한다.** 

```python
try:    
    num = input('값을 입력하시오 : ')
    print(int(num))
except:    
    print('숫자를 다시 입력해주세요.')
```

```
값을 입력하시오 : 값
숫자를 다시 입력해주세요.
```



---



### 2-2. as

> `as`  로 에러 메시지를 보여줄 수도 있다 

```python
try:
    empty_list = []
    print(empty_list[-1])
except IndexError as error:
    print(error)
```

```
list index out of range
```



---



### 2-3.  복수의 예외 처리

> tuple로 여러개의 예외를 지정하거나, 각각 다른 오류를 출력할 수 있다.
>
> 단, **에러가 순차적으로 수행**되므로, 가장 작은 범주부터 시작해야 한다.

```python
# 여러가지 예외를 지정하기
try:
    num = input('100으로 나눌 값을 입력하시오: ')
    print(100/int(num))
except (ValueError, ZeroDivisionError):
    print('무언가가 잘 못 되었습니다.')
    
# 오류의 종류에 따라 다른 메시지 출력하기.    
try:
    num = input('100으로 나눌 값을 입력하시오: ')
    100/int(num)
except ValueError:
    print('글자가 아닌 숫자를 입력해주세요')
except ZeroDivisionError:
    print('0으로는 나눗셈을 할 수 없습니다.')
```

```
100으로 나눌 값을 입력하시오: 값
무언가가 잘 못 되었습니다.
```

```
100으로 나눌 값을 입력하시오: 0
0으로는 나눗셈을 할 수 없습니다.
```



- `else`

  `else` 로 에러가 발생하지 않았을 때, 실행 시킬 문장을 지정한다.

```python
try:
    numbers = [1, 2, 3]
    number = numbers[2]
except IndexError:
    print('오류 발생')
else:
    print(number)
```

```
3
```



- `finally`

  `finally` 는 반드시 실행되어야 하는 코드에 활용한다. **예외 발생 여부와 관계없이 항상 실행된다.**

```python
try:
    languages = {'python': 'good'}
    languages['java']
except KeyError as err:
    print(f'{err}는 딕셔너리에 없는 키입니다.')
finally:
    print('감사합니다')
```

```
'java'는 딕셔너리에 없는 키입니다.
감사합니다
```



---



### 2-4. 예외 발생 시키기 (Exception Raising)



- `raise`

  `raise` 로 예외를 강제로 발생시킬 수 있다. 조용히 발생하는 논리 오류를 명시적으로 발생시키고 싶을 때 활용한다. 

```python
def my_div(num1, num2):
    if num2 == 0:
        raise Zerodivision('오류가 발생하였습니다.')
    elif type(num1) == str or type(num2) == str:
        raise ValueError('숫자를 넣어주세요')
    else:
        return num1 // num2
    pass

my_div('1', '5')
```

```
ValueError: 숫자를 넣어주세요
```



- `assert`

  `assert` 는 상태를 검증하는데 사용되고 무조건 `AssertionError` 가 발생한다. `raise` 와 달리 검증식이 거짓일 때만 발생한다.

|                | raise       | assert             |
| -------------- | ----------- | ------------------ |
| 용도/목적      | 예외의 발생 | 상태의 검증        |
| 예외 발생 시점 | 항상        | 검증식이 거짓일 때 |
| 예외 종류      | 지정한 오류 | AssertionError     |

정확한 오류 정보를 전달하기 위해서는 `raise`가 더 적합하다. 